/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:38d67831-8d06-4614-aca0-84bbe9e39996",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_qV2l7pnMM",
    "aws_user_pools_web_client_id": "6d7aujbimutsqv36jma64is9c3",
    "oauth": {},
    "aws_user_files_s3_bucket": "productimage173245-dev",
    "aws_user_files_s3_bucket_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://nvcqps4abzaapn6mvm46bzbifu.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-4kjeacmhp5dyjkzcl442njqtdu"
};


export default awsmobile;
